### ISSUE TITLE
No linebreak in DetailsPanel

### ISSUE THREAD

**Issue by ridoo** [GeoNode/geonode-mapstore-client#1854]
## Describe the bug

On Firefox, long lines of attributes within the Detailspanel do not break. Detailspanel shows an horizontal scrollbar instead. This is different from Chrome.

Firefox:

![image](https://github.com/user-attachments/assets/d7f49e37-49fd-4031-b3c2-eb94cbcf2ee2)

Chrome is ok:

![image](https://github.com/user-attachments/assets/dd74bac4-22ce-46f4-8cd4-e3672c27a581)

## Expected Behavior

Lines break the same way as in Chrome Browser

## Steps to Reproduce the Problem

  1. Open a dataset having attributes with long lines (browser resize does not resize the detail panel)
    - `master`: https://stable.demo.geonode.org/catalogue/#/dataset/10913 
    - `development`: https://development.demo.geonode.org/catalogue/#/dataset/583
  3. Open details panel (firefox)
  4. Open details panel (chrome)

## Specifications

  - GeoNode client version: `master` and `development`
  - Browser: Firefox
  - Installation type (vanilla, geonode-project): demo instances
  - Additional details:

**Comment by kilichenko-pixida** [comment]
@ridoo It seems like the poblem is not with long lines of attributes per se, but specifically with keywords, because they are links. If the title is very long, it seems to wrap around just fine in Firefox as well. Abd as for the keywords, adding the following css makes it work both in Chrome and Firefox:

`.gn-details-info-value > a {
    display: inline-block; 
}`

My guess is that this particular element styling isn't specified explicitly and Chrome and Firefox just have different default display modes. Unfortunately, I wasn't able to figure out how to actually make changes to front-end and would require some help to actually apply the change.

**Comment by kilichenko-pixida** [comment]
Created a [PR ](https://github.com/GeoNode/geonode-mapstore-client/pull/1909)for it.

**Comment by gannebamm** [comment]
fixed on our fork

**Comment by ridoo** [comment]
@gannebamm still an issue or did you re-open this one by accident?

**Comment by gannebamm** [comment]
@ridoo It is fixed in our fork, but I haven't tested it on master, yet
